export const todosTypes = Object.freeze({
  FETCH_TODOS: 'FETCH_TODOS',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAIL: 'FETCH_TODOS_FAIL',

  ADD_TODO: 'ADD_TODO',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAIL: 'ADD_TODO_FAIL',

  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAIL: 'DELETE_TODO_FAIL',

  COMPLETE_TODO: 'COMPLETE_TODO',
  COMPLETE_TODO_SUCCESS: 'COMPLETE_TODO_SUCCESS',
  COMPLETE_TODO_FAIL: 'COMPLETE_TODO_FAIL',

  TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
  TOGGLE_FAVORITE_SUCCESS: 'TOGGLE_FAVORITE_SUCCESS',
  TOGGLE_FAVORITE_FAIL: 'TOGGLE_FAVORITE_FAIL',

  EDIT_TODO: 'EDIT_TODO',
  EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
  EDIT_TODO_FAIL: 'EDIT_TODO_FAIL',
});
